spring: 
  application: 
    name: busca-tipos-comida-service
  h2:
    console:
     settings:
      trace: true 
server: 
  port: 6060 
 
eureka: 
  client: 
    service-url: 
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}