spring: 
  application: 
    name: restaurantes-api
  h2:
    console:
     settings:
      trace: true 
server: 
  port: 6061
 
eureka: 
  client: 
    service-url: 
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}